# application path
server:
  servlet:
    context-path: /api

# database connection
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/vehicle
    username: postgres
    password: password
    pool-size: 30